create database ticket;
use ticket;
CREATE TABLE Users (
    UserID INT AUTO_INCREMENT PRIMARY KEY,
    Username VARCHAR(255) NOT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL UNIQUE
);
CREATE TABLE Flight (
    FlyID INT PRIMARY KEY AUTO_INCREMENT,
    StartPoint VARCHAR(255) NOT NULL,
    FinishPoint VARCHAR(255) NOT NULL,
    StartDate DATETIME NOT NULL,
    FinishDate DATETIME NOT NULL,
    PriceTicket DECIMAL(10, 2) NOT NULL,
    CountTicket INT NOT NULL
);
CREATE TABLE Tickets (
    UserID INT NOT NULL,
    FlyID INT NOT NULL,
    TicketID INT AUTO_INCREMENT PRIMARY KEY,
    Seat VARCHAR(10) NOT NULL,
    FOREIGN KEY (UserID) REFERENCES Users(UserID),
    FOREIGN KEY (FlyID) REFERENCES Flight(FlyID)
);
CREATE TABLE SeatFly (
    SeatID INT AUTO_INCREMENT PRIMARY KEY,
    Seat VARCHAR(10) NOT NULL
);